export const itemContainer: string;
export const title: string;
export const body: string;
export const description: string;
export const selected: string;
export const expanded: string;
export const unexpanding: string;
export const expanding: string;
export const buttonsContainer: string;
